name: Build exe

on:
  push:
    branches: [ main, dev ]

jobs:
  exe:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      timeout-minutes: 1


    - name: Set up Python 3
      uses: actions/setup-python@v2
      timeout-minutes: 5
      with:
        python-version: 3.8

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: '16.8'

    - uses: ilammy/msvc-dev-cmd@v1

    - name: Setup pip cache
      uses: actions/cache@v2
      timeout-minutes: 5
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install poetry & others
      run: python -m pip install poetry requests wheel

    - name: Run Poetry
      run: |
            python -m poetry install
            python -m poetry build

    - name: Install nuitka & pyinstaller
      run: poetry run pip install nuitka pyinstaller pywin32 py2exe

    - name: Buid exe using pyinstaller
      run: poetry run pyinstaller -F bravepatcher/gui.py

    - name: Buid exe using pyinstaller
      run: poetry run build_exe bravepatcher/gui.py


    - name: Create artifact
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: dist
        path: '*dist/'

    - name: Create artifact for json file
      uses: actions/upload-artifact@v2
      with:
        name: gui_dist
        path: gui.dist/